---
branches:
  only:
    - master
    - develop
language: ruby
bundler_args: --without development
script:
  - "bundle exec rake syntax"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
notifications:
  email: 'uC986brCKu8eZmasm4G8iW4YR3hbCi@api.pushover.net'
